from app import app, db, Product

def populate_products():
    productos = [
        # bimbo
        {
            "supplier": "bimbo",
            "name": "Mantecadas Vainilla",
            "description": "Deliciosas mantecadas sabor vainilla, suaves y esponjosas.",
            "price_cents": 3500,
            "image": "mantecadas_vainilla_625g.jpg",
            "brand": "Bimbo",
            "weight": "625g",
            "ingredients": "Harina de trigo, azúcar, huevo, aceite vegetal, saborizante de vainilla.",
            "allergens": "Gluten, huevo",
            "nutritional_info": "Energía: 350kcal por porción. Grasas: 15g. Azúcares: 20g.",
            "stock": 20
        },
        {
            "supplier": "bimbo",
            "name": "Pan Blanco Grande",
            "description": "Pan blanco suave, ideal para sándwiches y tostadas.",
            "price_cents": 2800,
            "image": "pan_blanco_680g.jpg",
            "brand": "Bimbo",
            "weight": "680g",
            "ingredients": "Harina de trigo, agua, levadura, sal, azúcar.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 250kcal por porción. Fibra: 2g.",
            "stock": 30
        },
        {
            "supplier": "bimbo",
            "name": "Donas Azucaradas",
            "description": "Donas cubiertas de azúcar, perfectas para acompañar tu café.",
            "price_cents": 3200,
            "image": "donas_azucaradas_6p.jpg",
            "brand": "Bimbo",
            "weight": "6 piezas",
            "ingredients": "Harina de trigo, azúcar, huevo, aceite vegetal.",
            "allergens": "Gluten, huevo",
            "nutritional_info": "Energía: 400kcal por porción. Azúcares: 22g.",
            "stock": 15
        },
        {
            "supplier": "bimbo",
            "name": "Roles Canela",
            "description": "Roles de canela con glaseado dulce.",
            "price_cents": 4000,
            "image": "roles_canela_4p.jpg",
            "brand": "Bimbo",
            "weight": "4 piezas",
            "ingredients": "Harina de trigo, azúcar, canela, huevo, aceite vegetal.",
            "allergens": "Gluten, huevo",
            "nutritional_info": "Energía: 420kcal por porción. Azúcares: 24g.",
            "stock": 10
        },
        {
            "supplier": "bimbo",
            "name": "Pan Integral",
            "description": "Pan integral saludable, fuente de fibra.",
            "price_cents": 3000,
            "image": "pan_integral_680g.jpg",
            "brand": "Bimbo",
            "weight": "680g",
            "ingredients": "Harina integral de trigo, agua, levadura, sal.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 220kcal por porción. Fibra: 5g.",
            "stock": 25
        },
        {
            "supplier": "bimbo",
            "name": "Panqué Marmoleado",
            "description": "Panqué marmoleado sabor vainilla y chocolate, suave y delicioso.",
            "price_cents": 3400,
            "image": "panque_marmoleado_255g.jpg",
            "brand": "Bimbo",
            "weight": "255g",
            "ingredients": "Harina de trigo, azúcar, huevo, aceite vegetal, cocoa.",
            "allergens": "Gluten, huevo",
            "nutritional_info": "Energía: 370kcal por porción. Azúcares: 18g.",
            "stock": 18
        },
        {
            "supplier": "bimbo",
            "name": "Medias Noches",
            "description": "Pan suave tipo hot dog, ideal para preparar medias noches.",
            "price_cents": 3300,
            "image": "medias_noches_320g.jpg",
            "brand": "Bimbo",
            "weight": "320g",
            "ingredients": "Harina de trigo, azúcar, huevo, aceite vegetal.",
            "allergens": "Gluten, huevo",
            "nutritional_info": "Energía: 260kcal por porción. Azúcares: 7g.",
            "stock": 22
        },
        # gamesa
        {
            "supplier": "gamesa",
            "name": "Galletas Marías",
            "description": "Galletas clásicas Marías, perfectas para acompañar leche o café.",
            "price_cents": 1500,
            "image": "galletas_marias_170g.jpg",
            "brand": "Gamesa",
            "weight": "170g",
            "ingredients": "Harina de trigo, azúcar, huevo, aceite vegetal.",
            "allergens": "Gluten, huevo",
            "nutritional_info": "Energía: 120kcal por porción. Azúcares: 8g.",
            "stock": 40
        },
        {
            "supplier": "gamesa",
            "name": "Galletas Emperador Chocolate",
            "description": "Galletas rellenas de chocolate, crujientes y deliciosas.",
            "price_cents": 2200,
            "image": "galletas_emperador_100g.jpg",
            "brand": "Gamesa",
            "weight": "100g",
            "ingredients": "Harina de trigo, azúcar, cacao, aceite vegetal.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 150kcal por porción. Azúcares: 10g.",
            "stock": 35
        },
        {
            "supplier": "gamesa",
            "name": "Galletas Arcoiris",
            "description": "Galletas con chispas de colores, divertidas y sabrosas.",
            "price_cents": 2000,
            "image": "galletas_arcoiris_120g.jpg",
            "brand": "Gamesa",
            "weight": "120g",
            "ingredients": "Harina de trigo, azúcar, colorantes, aceite vegetal.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 130kcal por porción. Azúcares: 9g.",
            "stock": 20
        },
        {
            "supplier": "gamesa",
            "name": "Galletas Saladitas",
            "description": "Galletas saladas crujientes, ideales para botanas.",
            "price_cents": 1800,
            "image": "galletas_saladitas_150g.jpg",
            "brand": "Gamesa",
            "weight": "150g",
            "ingredients": "Harina de trigo, sal, aceite vegetal.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 110kcal por porción. Sodio: 200mg.",
            "stock": 25
        },
        {
            "supplier": "gamesa",
            "name": "Galletas Chokis",
            "description": "Galletas con chispas de chocolate, favoritas de todos.",
            "price_cents": 2500,
            "image": "galletas_chokis_90g.jpg",
            "brand": "Gamesa",
            "weight": "90g",
            "ingredients": "Harina de trigo, azúcar, chispas de chocolate.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 160kcal por porción. Azúcares: 12g.",
            "stock": 30
        },
        {
            "supplier": "gamesa",
            "name": "Galletas Florentinas",
            "description": "Galletas con relleno sabor fresa y cobertura de chocolate.",
            "price_cents": 2400,
            "image": "galletas_florentinas_90g.jpg",
            "brand": "Gamesa",
            "weight": "90g",
            "ingredients": "Harina de trigo, azúcar, fresa, chocolate, aceite vegetal.",
            "allergens": "Gluten, leche",
            "nutritional_info": "Energía: 180kcal por porción. Azúcares: 12g.",
            "stock": 16
        },
        {
            "supplier": "gamesa",
            "name": "Galletas Crackets",
            "description": "Galletas saladas tipo cracker, perfectas para botanas.",
            "price_cents": 1700,
            "image": "galletas_crackets_170g.jpg",
            "brand": "Gamesa",
            "weight": "170g",
            "ingredients": "Harina de trigo, aceite vegetal, sal.",
            "allergens": "Gluten",
            "nutritional_info": "Energía: 120kcal por porción. Sodio: 180mg.",
            "stock": 20
        },
        # sabritas
        {
            "supplier": "sabritas",
            "name": "Papas Clásicas",
            "description": "Papas fritas clásicas, crujientes y saladas.",
            "price_cents": 1800,
            "image": "papas_clasicas_45g.jpg",
            "brand": "Sabritas",
            "weight": "45g",
            "ingredients": "Papa, aceite vegetal, sal.",
            "allergens": "",
            "nutritional_info": "Energía: 150kcal por porción. Grasas: 10g.",
            "stock": 50
        },
        {
            "supplier": "sabritas",
            "name": "Cheetos",
            "description": "Botana de maíz con queso, sabor intenso.",
            "price_cents": 1700,
            "image": "cheetos_40g.jpg",
            "brand": "Sabritas",
            "weight": "40g",
            "ingredients": "Maíz, queso, aceite vegetal.",
            "allergens": "Lácteos",
            "nutritional_info": "Energía: 140kcal por porción. Grasas: 8g.",
            "stock": 45
        },
        {
            "supplier": "sabritas",
            "name": "Doritos Nacho",
            "description": "Totopos de maíz sabor nacho, perfectos para compartir.",
            "price_cents": 1900,
            "image": "doritos_nacho_52g.jpg",
            "brand": "Sabritas",
            "weight": "52g",
            "ingredients": "Maíz, queso, especias, aceite vegetal.",
            "allergens": "Lácteos",
            "nutritional_info": "Energía: 160kcal por porción. Grasas: 9g.",
            "stock": 40
        },
        {
            "supplier": "sabritas",
            "name": "Ruffles Queso",
            "description": "Papas onduladas sabor queso, extra crujientes.",
            "price_cents": 2100,
            "image": "ruffles_queso_45g.jpg",
            "brand": "Sabritas",
            "weight": "45g",
            "ingredients": "Papa, queso, aceite vegetal.",
            "allergens": "Lácteos",
            "nutritional_info": "Energía: 170kcal por porción. Grasas: 11g.",
            "stock": 35
        },
        {
            "supplier": "sabritas",
            "name": "Papas Adobadas",
            "description": "Papas fritas sabor adobadas, con especias mexicanas.",
            "price_cents": 2000,
            "image": "papas_adobadas_45g.jpg",
            "brand": "Sabritas",
            "weight": "45g",
            "ingredients": "Papa, especias, aceite vegetal.",
            "allergens": "",
            "nutritional_info": "Energía: 155kcal por porción. Grasas: 10g.",
            "stock": 30
        },
        {
            "supplier": "sabritas",
            "name": "Cacahuates Japoneses",
            "description": "Cacahuates cubiertos con una crujiente capa de harina de trigo.",
            "price_cents": 2000,
            "image": "cacahuates_japoneses_60g.jpg",
            "brand": "Sabritas",
            "weight": "60g",
            "ingredients": "Cacahuate, harina de trigo, azúcar, salsa de soya.",
            "allergens": "Cacahuate, gluten, soya",
            "nutritional_info": "Energía: 320kcal por 60g.",
            "stock": 24
        },
        {
            "supplier": "sabritas",
            "name": "Rancheritos",
            "description": "Botana de maíz sabor a chile y especias, muy crujiente.",
            "price_cents": 1600,
            "image": "rancheritos_62g.jpg",
            "brand": "Sabritas",
            "weight": "62g",
            "ingredients": "Harina de maíz, aceite vegetal, chile, especias.",
            "allergens": "Puede contener soya.",
            "nutritional_info": "Energía: 290kcal por 62g.",
            "stock": 26
        },
        # la_costena
        {
            "supplier": "la_costena",
            "name": "Chiles Jalapeños en Escabeche",
            "description": "Chiles jalapeños en rodajas, ideales para acompañar tus platillos.",
            "price_cents": 2200,
            "image": "jalapenos_escabeche_220g.jpg",
            "brand": "La Costeña",
            "weight": "220g",
            "ingredients": "Chiles jalapeños, zanahoria, vinagre, especias.",
            "allergens": "",
            "nutritional_info": "Energía: 25kcal por 30g.",
            "stock": 30
        },
        {
            "supplier": "la_costena",
            "name": "Frijoles Negros Refritos",
            "description": "Frijoles negros refritos listos para servir.",
            "price_cents": 1800,
            "image": "frijoles_negros_refritos_430g.jpg",
            "brand": "La Costeña",
            "weight": "430g",
            "ingredients": "Frijol negro, aceite vegetal, sal.",
            "allergens": "",
            "nutritional_info": "Energía: 90kcal por 100g.",
            "stock": 25
        },
        {
            "supplier": "la_costena",
            "name": "Elote Dorado en Grano",
            "description": "Elote dorado en grano, ideal para ensaladas y guisos.",
            "price_cents": 2100,
            "image": "elote_dorado_220g.jpg",
            "brand": "La Costeña",
            "weight": "220g",
            "ingredients": "Elote, agua, sal.",
            "allergens": "",
            "nutritional_info": "Energía: 70kcal por 100g.",
            "stock": 20
        },
        {
            "supplier": "la_costena",
            "name": "Salsa Verde",
            "description": "Salsa verde lista para servir, perfecta para tacos y antojitos.",
            "price_cents": 1700,
            "image": "salsa_verde_210g.jpg",
            "brand": "La Costeña",
            "weight": "210g",
            "ingredients": "Tomatillo, chile, cebolla, ajo, sal.",
            "allergens": "",
            "nutritional_info": "Energía: 20kcal por 30g.",
            "stock": 35
        },
        {
            "supplier": "la_costena",
            "name": "Salsa Catsup",
            "description": "Catsup clásica, ideal para acompañar botanas y comidas rápidas.",
            "price_cents": 1900,
            "image": "catsup_370g.jpg",
            "brand": "La Costeña",
            "weight": "370g",
            "ingredients": "Tomate, azúcar, vinagre, sal, especias.",
            "allergens": "",
            "nutritional_info": "Energía: 90kcal por 30g.",
            "stock": 28
        },
        {
            "supplier": "la_costena",
            "name": "Chiles Chipotles Adobados",
            "description": "Chiles chipotles adobados en salsa, sabor ahumado y picante.",
            "price_cents": 2300,
            "image": "chipotles_adobados_220g.jpg",
            "brand": "La Costeña",
            "weight": "220g",
            "ingredients": "Chile chipotle, tomate, vinagre, especias.",
            "allergens": "",
            "nutritional_info": "Energía: 40kcal por 30g.",
            "stock": 22
        },
        {
            "supplier": "la_costena",
            "name": "Nopales en Trozos",
            "description": "Nopales en trozos cocidos, listos para ensaladas y guisos.",
            "price_cents": 2000,
            "image": "nopales_trozos_220g.jpg",
            "brand": "La Costeña",
            "weight": "220g",
            "ingredients": "Nopal, agua, sal.",
            "allergens": "",
            "nutritional_info": "Energía: 15kcal por 100g.",
            "stock": 18
        },
        # barcel
        {
            "supplier": "barcel",
            "name": "Takis Fuego",
            "description": "Botana de maíz enrollada sabor chile y limón, extra picante.",
            "price_cents": 1500,
            "image": "takis_fuego_62g.jpg",
            "brand": "Barcel",
            "weight": "62g",
            "ingredients": "Harina de maíz, aceite vegetal, condimentos, chile, limón.",
            "allergens": "Puede contener soya y gluten.",
            "nutritional_info": "Energía: 280kcal por 62g.",
            "stock": 40
        },
        {
            "supplier": "barcel",
            "name": "Chips Jalapeño",
            "description": "Papas fritas sabor jalapeño, crujientes y picantes.",
            "price_cents": 1700,
            "image": "chips_jalapeno_50g.jpg",
            "brand": "Barcel",
            "weight": "50g",
            "ingredients": "Papa, aceite vegetal, condimentos, jalapeño.",
            "allergens": "Puede contener soya.",
            "nutritional_info": "Energía: 250kcal por 50g.",
            "stock": 35
        },
        {
            "supplier": "barcel",
            "name": "Runners",
            "description": "Botana de maíz sabor queso y chile.",
            "price_cents": 1400,
            "image": "runners_queso_50g.jpg",
            "brand": "Barcel",
            "weight": "50g",
            "ingredients": "Harina de maíz, aceite vegetal, queso, chile.",
            "allergens": "Contiene leche y puede contener soya.",
            "nutritional_info": "Energía: 240kcal por 50g.",
            "stock": 30
        },
        {
            "supplier": "barcel",
            "name": "Hot Nuts",
            "description": "Cacahuates enchilados, crujientes y picantes.",
            "price_cents": 1800,
            "image": "hot_nuts_60g.jpg",
            "brand": "Barcel",
            "weight": "60g",
            "ingredients": "Cacahuate, harina de trigo, chile, sal.",
            "allergens": "Contiene cacahuate y trigo.",
            "nutritional_info": "Energía: 320kcal por 60g.",
            "stock": 28
        },
        {
            "supplier": "barcel",
            "name": "Churritos Maíz",
            "description": "Churritos de maíz sabor chile y limón.",
            "price_cents": 1300,
            "image": "churritos_maiz_50g.jpg",
            "brand": "Barcel",
            "weight": "50g",
            "ingredients": "Harina de maíz, aceite vegetal, chile, limón.",
            "allergens": "Puede contener soya.",
            "nutritional_info": "Energía: 230kcal por 50g.",
            "stock": 32
        },
        {
            "supplier": "barcel",
            "name": "Takis Xtra Hot",
            "description": "Botana de maíz enrollada sabor chile extra picante.",
            "price_cents": 1550,
            "image": "takis_xtrahot_62g.jpg",
            "brand": "Barcel",
            "weight": "62g",
            "ingredients": "Harina de maíz, aceite vegetal, condimentos, chile.",
            "allergens": "Puede contener soya y gluten.",
            "nutritional_info": "Energía: 285kcal por 62g.",
            "stock": 26
        }
    ]

    with app.app_context():
        db.create_all()
        for prod in productos:
            existe = Product.query.filter_by(name=prod["name"], supplier=prod["supplier"]).first()
            if not existe:
                db.session.add(Product(**prod))
        db.session.commit()
        print("Productos reales agregados correctamente.")

if __name__ == "__main__":
    populate_products()